In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.1.4'

In [4]:
data=pd.read_csv("netflix1.csv")
data

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [10]:
#this is for the Displaying of the First 5 Files of the Data Set
data.head(10)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
5,s9,TV Show,The Great British Baking Show,Andy Devonshire,United Kingdom,9/24/2021,2021,TV-14,9 Seasons,"British TV Shows, Reality TV"
6,s10,Movie,The Starling,Theodore Melfi,United States,9/24/2021,2021,PG-13,104 min,"Comedies, Dramas"
7,s939,Movie,Motu Patlu in the Game of Zones,Suhas Kadav,India,5/1/2021,2019,TV-Y7,87 min,"Children & Family Movies, Comedies, Music & Mu..."
8,s13,Movie,Je Suis Karl,Christian Schwochow,Germany,9/23/2021,2021,TV-MA,127 min,"Dramas, International Movies"
9,s940,Movie,Motu Patlu in Wonderland,Suhas Kadav,India,5/1/2021,2013,TV-Y7,76 min,"Children & Family Movies, Music & Musicals"

In [11]:
# this is for the displaying the tailing 
data.tail(2)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [12]:
#this is for the information 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [14]:
# this is for the Steps that we will perform here 
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Remove the NaN values from the dataset
Check for some more Transformations
What is redundancy here 
Duplicate (same data in two columns)
Useless (don't contribute to your analysis)
Irrelevant (not related to your goal)
"""

'Deleting redundant columns.\nRenaming the columns.\nDropping duplicates.\nRemove the NaN values from the dataset\nCheck for some more Transformations'

In [24]:
#for printing the columns of the Data Set 

data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'duration', 'listed_in'],
      dtype='object')

In [25]:
#lets drop the rating columns 
#if having multiple columns then just Pass the List of the columns 
if 'rating' in data.columns:
    data.drop(columns="rating", inplace=True)

In [26]:
# rating column will still show up here but if we do inplace true when w were dropping this every thing will be fixed 
data.head()

,show_id,type,title,director,country,date_added,release_year,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [34]:
#Now lets Capalized the names of the columns 
new_column_names = []
for i in data.columns:
    new_column_names.append(i.capitalize())  # append instead of print

data.columns = new_column_names
data

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,1 Season,Kids' TV

In [33]:
#Noe give them the names 
data.columns=new_column_names
data.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [36]:
#checking duplicates
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8785    False
8786    False
8787    False
8788    False
8789    False
Length: 8790, dtype: bool

In [5]:
#this is for the Sum of the Duplicated f the Sum
data.duplicated().sum()

0

In [6]:
data.drop_duplicates(inplace=True)

In [7]:
#this is for the

In [9]:
# Check for Missing Values
data.isna().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [10]:
#
data.dropna(inplace=True)

In [11]:
data.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [12]:
data["show_id"].unique()

array(['s1', 's3', 's6', ..., 's8801', 's8784', 's8786'], dtype=object)

In [21]:
# Safely removes the 's' only if it's at the beginning
data["show_id"] = data["show_id"].str.lstrip("s")

In [22]:
data.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [23]:
#this is for the Checking of the type 
type(data["show_id"][0])

str

In [51]:
data["show_id"] = data["show_id"].astype(int)
type(data["show_id"][0])
data = data.sort_values("show_id", ascending=True)
data
data = data.sort_values("country", ascending=True)
data

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2786,2787,Movie,A Life of Speed: The Juan Manuel Fangio Story,Francisco Macri,Argentina,3-20-2020,2020,TV-14,93 min,"Documentaries, International Movies, Sports Mo..."
7785,7801,TV Show,Psiconautas,Not Given,Argentina,4-15-2018,2016,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh..."
1713,1714,Movie,Memories of a Teenager,Lucas Santa Ana,Argentina,11-12-2020,2019,TV-MA,97 min,"Dramas, International Movies, LGBTQ Movies"
7730,7746,Movie,"Pizza, birra, faso","Israel Adrián Caetano, Bruno Stagnaro",Argentina,3-15-2018,1998,TV-MA,81 min,"Dramas, International Movies"
303,304,Movie,Esperando la carroza,Alejandro Doria,Argentina,8-5-2021,1985,TV-MA,95 min,"Comedies, Cult Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
7104,7115,Movie,Jackpot,Dustin Nguyen,Vietnam,10-6-2018,2015,TV-14,92 min,"Comedies, Dramas, International Movies"
6521,6528,Movie,Conjuring Spirit,Van M. Pham,Vietnam,8-28-2018,2014,TV-MA,112 min,"Horror Movies, International Movies, Thrillers"
6808,6817,Movie,Furie,Le Van Kiet,Vietnam,9-25-2019,2019,TV-MA,97 min,"Action & Adventure, Dramas, International Movies"
5611,5613,Movie,Hitler - A Career,"Joachim Fest, Christian Herrendoerfer",West Germany,2-10-2017,1977,TV-MA,150 min,"Documentaries, International Movies"
2446,2447,Movie,Cook Off,Tomas Brickhill,Zimbabwe,6-1-2020,2017,TV-G,100 min,"Comedies, International Movies, Romantic Movies"

In [52]:
data["date_added"] = data["date_added"].apply(lambda x : x.replace("/","-"))
                                              
data

data.to_csv("cleaneddata.csv",index=False)

In [8]:
# Selection using loc for specific rows and columns
print("Selection using loc:")
display(data.loc[0:5, ['title', 'country', 'type']])

Selection using loc:

                              title         country     type
0              Dick Johnson Is Dead   United States    Movie
1                         Ganglands          France  TV Show
2                     Midnight Mass   United States  TV Show
3  Confessions of an Invisible Girl          Brazil    Movie
4                           Sankofa   United States    Movie
5     The Great British Baking Show  United Kingdom  TV Show

In [9]:
# Selection using iloc for specific rows and columns (e.g., first 5 rows, first 3 columns)
print("Selection using iloc:")
display(data.iloc[:5, :3])

Selection using iloc:

  show_id     type                             title
0      s1    Movie              Dick Johnson Is Dead
1      s3  TV Show                         Ganglands
2      s6  TV Show                     Midnight Mass
3     s14    Movie  Confessions of an Invisible Girl
4      s8    Movie                           Sankofa

In [10]:
# Filter all 'Movie' type with release_year > 2020
filtered_data = data[(data['type'] == 'Movie') & (data['release_year'] > 2020)]
display(filtered_data.head())

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
6,s10,Movie,The Starling,Theodore Melfi,United States,9/24/2021,2021,PG-13,104 min,"Comedies, Dramas"
8,s13,Movie,Je Suis Karl,Christian Schwochow,Germany,9/23/2021,2021,TV-MA,127 min,"Dramas, International Movies"
12,s852,Movie,99 Songs (Tamil),Not Given,Pakistan,5/21/2021,2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals"
13,s471,Movie,Bridgerton - The Afterparty,"Krysia Plonka, Kristian Mercado",United States,7/13/2021,2021,TV-14,39 min,Movies

In [11]:
# Filter TV Shows from 'India' using query
india_tv_shows = data.query("country == 'India' and type == 'TV Show'")
display(india_tv_shows.head())

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
409,s298,TV Show,Navarasa,"Bejoy Nambiar, Priyadarshan, Karthik Narain, V...",India,8/6/2021,2021,TV-MA,1 Season,TV Shows
954,s912,TV Show,Sab Jholmaal Hai,Vijay Roche,India,5/7/2021,2017,TV-Y7,2 Seasons,"Kids' TV, TV Comedies"
1225,s1294,TV Show,Pitta Kathalu,"Tharun Bhascker Dhaassyam, B. V. Nandini Reddy...",India,2/19/2021,2021,TV-MA,1 Season,"International TV Shows, TV Dramas"
1371,s1521,TV Show,Paava Kadhaigal,"Sudha Kongara, Vignesh Shivan, Gautham Vasudev...",India,12/18/2020,2020,TV-MA,1 Season,"International TV Shows, TV Dramas"
2387,s3037,TV Show,Jamtara - Sabka Number Ayega,Soumendra Padhi,India,1/10/2020,2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas"

In [12]:
# Group by 'country' and 'type', then count titles and find mean release year
agg_results = data.groupby(['country', 'type']).agg({
    'title': 'count',
    'release_year': 'mean'
}).rename(columns={'title': 'count', 'release_year': 'avg_release_year'})

display(agg_results.sort_values(by='count', ascending=False).head(10))

                        count  avg_release_year
country        type
United States  Movie     2395       2011.926931
India          Movie      976       2011.668033
United States  TV Show    845       2016.550296
United Kingdom Movie      387       2013.519380
Pakistan       TV Show    350       2017.174286
Not Given      Movie      257       2016.696498
United Kingdom TV Show    251       2015.808765
Canada         Movie      187       2016.192513
Japan          TV Show    172       2014.819767
South Korea    TV Show    165       2017.030303

In [13]:
# Count number of titles per rating
print("Top 5 countries by content count:")
display(data['country'].value_counts().head(5))

Top 5 countries by content count:

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
Name: count, dtype: int64

In [14]:
# Pivot table showing count of Movies vs TV Shows per country (top 10 countries)
top_countries = data['country'].value_counts().head(10).index
pivot_df = data[data['country'].isin(top_countries)].pivot_table(
    index='country', 
    columns='type', 
    values='title', 
    aggfunc='count',
    fill_value=0
)
display(pivot_df)

type            Movie  TV Show
country
Canada            187       84
France            148       65
India             976       81
Japan              87      172
Not Given         257       30
Pakistan           71      350
South Korea        49      165
Spain             129       53
United Kingdom    387      251
United States    2395      845

In [15]:
regions_data = pd.DataFrame({
    'country': ['United States', 'India', 'United Kingdom', 'Japan', 'South Korea'],
    'region': ['North America', 'South Asia', 'Europe', 'East Asia', 'East Asia']
})

# Perform a left merge
merged_data = data.merge(regions_data, on='country', how='left')
display(merged_data[['title', 'country', 'region']].head(10))

                              title         country         region
0              Dick Johnson Is Dead   United States  North America
1                         Ganglands          France            NaN
2                     Midnight Mass   United States  North America
3  Confessions of an Invisible Girl          Brazil            NaN
4                           Sankofa   United States  North America
5     The Great British Baking Show  United Kingdom         Europe
6                      The Starling   United States  North America
7   Motu Patlu in the Game of Zones           India     South Asia
8                      Je Suis Karl         Germany            NaN
9          Motu Patlu in Wonderland           India     South Asia

In [16]:
# Concat: Split and recombine (stacking Movies and TV Shows vertically)
movies = data[data['type'] == 'Movie'].head(3)
tv_shows = data[data['type'] == 'TV Show'].head(3)
combined = pd.concat([movies, tv_shows], axis=0)
display(combined[['title', 'type']])

                              title     type
0              Dick Johnson Is Dead    Movie
3  Confessions of an Invisible Girl    Movie
4                           Sankofa    Movie
1                         Ganglands  TV Show
2                     Midnight Mass  TV Show
5     The Great British Baking Show  TV Show

In [17]:
# Use map for simple value replacement (e.g., shorter labels for types)
data['short_type'] = data['type'].map({'Movie': 'M', 'TV Show': 'TV'})

# Rename columns
data = data.rename(columns={'listed_in': 'genres'})

display(data[['title', 'short_type', 'genres']].head())

,title,short_type,genres
0,Dick Johnson Is Dead,M,Documentaries
1,Ganglands,TV,"Crime TV Shows, International TV Shows, TV Act..."
2,Midnight Mass,TV,"TV Dramas, TV Horror, TV Mysteries"
3,Confessions of an Invisible Girl,M,"Children & Family Movies, Comedies"
4,Sankofa,M,"Dramas, Independent Movies, International Movies"

In [18]:
# Melt: Reshape for analysis (taking title, type, and release_year and making them key-value pairs)
melted_df = data.head(5).melt(id_vars=['show_id'], value_vars=['title', 'type'], var_name='attribute', value_name='value')
display(melted_df)

  show_id attribute                             value
0      s1     title              Dick Johnson Is Dead
1      s3     title                         Ganglands
2      s6     title                     Midnight Mass
3     s14     title  Confessions of an Invisible Girl
4      s8     title                           Sankofa
5      s1      type                             Movie
6      s3      type                           TV Show
7      s6      type                           TV Show
8     s14      type                             Movie
9      s8      type                             Movie

In [19]:
# str.contains: Find titles containing 'Action' or 'Drama' in genres (case insensitive)
drama_titles = data[data['genres'].str.contains('Drama', case=False, na=False)]
print("Sample Drama Titles:")
display(drama_titles[['title', 'genres']].head())

# str.split: Split genres by comma and expand (look at the first title's genres)
print("Split genres for first 5 titles:")
display(data['genres'].str.split(',').head(5))

# str.extract: Extract first word of title
data['first_word'] = data['title'].str.extract(r'^(\w+)')
display(data[['title', 'first_word']].head())

Sample Drama Titles:

               title                                            genres
2      Midnight Mass                TV Dramas, TV Horror, TV Mysteries
4            Sankofa  Dramas, Independent Movies, International Movies
6       The Starling                                  Comedies, Dramas
8       Je Suis Karl                      Dramas, International Movies
12  99 Songs (Tamil)    Dramas, International Movies, Music & Musicals

Split genres for first 5 titles:

0                                      [Documentaries]
1    [Crime TV Shows,  International TV Shows,  TV ...
2               [TV Dramas,  TV Horror,  TV Mysteries]
3                [Children & Family Movies,  Comedies]
4    [Dramas,  Independent Movies,  International M...
Name: genres, dtype: object

                              title   first_word
0              Dick Johnson Is Dead         Dick
1                         Ganglands    Ganglands
2                     Midnight Mass     Midnight
3  Confessions of an Invisible Girl  Confessions
4                           Sankofa      Sankofa

In [20]:
# Convert date_added to actual datetime objects
data['date_added'] = pd.to_datetime(data['date_added'])

# Extract parts of the date
data['added_year'] = data['date_added'].dt.year
data['added_month'] = data['date_added'].dt.month_name()
data['added_day_name'] = data['date_added'].dt.day_name()

display(data[['title', 'date_added', 'added_year', 'added_month', 'added_day_name']].head())

,title,date_added,added_year,added_month,added_day_name
0,Dick Johnson Is Dead,2021-09-25,2021,September,Saturday
1,Ganglands,2021-09-24,2021,September,Friday
2,Midnight Mass,2021-09-24,2021,September,Friday
3,Confessions of an Invisible Girl,2021-09-22,2021,September,Wednesday
4,Sankofa,2021-09-24,2021,September,Friday

In [21]:
# describe: Statistical summary of numerical columns
print("Statistical Summary:")
display(data.describe())

# Mean and Median of release_year
print(f"Mean Release Year: {data['release_year'].mean():.2f}")
print(f"Median Release Year: {data['release_year'].median()}")

# Correlation (between numerical columns - here we only have release_year and added_year)
print("\nCorrelation Matrix:")
display(data[['release_year', 'added_year']].corr())

Statistical Summary:

                          date_added  release_year   added_year
count                           8790   8790.000000  8790.000000
mean   2019-05-17 21:44:01.638225408   2014.183163  2018.873606
min              2008-01-01 00:00:00   1925.000000  2008.000000
25%              2018-04-06 00:00:00   2013.000000  2018.000000
50%              2019-07-03 00:00:00   2017.000000  2019.000000
75%              2020-08-19 18:00:00   2019.000000  2020.000000
max              2021-09-25 00:00:00   2021.000000  2021.000000
std                              NaN      8.825466     1.573568

Mean Release Year: 2014.18
Median Release Year: 2017.0

Correlation Matrix:

              release_year  added_year
release_year      1.000000    0.111624
added_year        0.111624    1.000000

In [22]:
# Count releases per year
yearly_counts = data.groupby('release_year').size().reset_index(name='count').sort_values('release_year')

# cumsum: Cumulative count of releases over time
yearly_counts['cumulative_total'] = yearly_counts['count'].cumsum()

# rolling: 5-year moving average of release counts
yearly_counts['moving_avg_5yr'] = yearly_counts['count'].rolling(window=5).mean()

# shift: Difference in count compared to previous year
yearly_counts['diff_previous_year'] = yearly_counts['count'] - yearly_counts['count'].shift(1)

display(yearly_counts.tail(10))

    release_year  count  cumulative_total  moving_avg_5yr  diff_previous_year
64          2012    236              1945           180.0                51.0
65          2013    286              2231           210.2                50.0
66          2014    352              2583           250.2                66.0
67          2015    555              3138           322.8               203.0
68          2016    901              4039           466.0               346.0
69          2017   1030              5069           624.8               129.0
70          2018   1146              6215           796.8               116.0
71          2019   1030              7245           932.4              -116.0
72          2020    953              8198          1012.0               -77.0
73          2021    592              8790           950.2              -361.0

In [23]:
# pd.cut: Bin release years into decades
bins = [1920, 1980, 1990, 2000, 2010, 2020, 2030]
labels = ['Pre-80s', '80s', '90s', '2000s', '2010s', '2020s']
data['decade'] = pd.cut(data['release_year'], bins=bins, labels=labels)
display(data[['title', 'release_year', 'decade']].head())

# pd.get_dummies: One-hot encoding for the 'short_type' column
dummies = pd.get_dummies(data['short_type'], prefix='type')
display(dummies.head())

# MultiIndex example: Grouping by Decade and Country
multi_indexed = data.groupby(['decade', 'country']).size().head(10)
print("MultiIndex Series (Decade, Country):")
print(multi_indexed)

                              title  release_year decade
0              Dick Johnson Is Dead          2020  2010s
1                         Ganglands          2021  2020s
2                     Midnight Mass          2021  2020s
3  Confessions of an Invisible Girl          2021  2020s
4                           Sankofa          1993    90s

   type_M  type_TV
0    True    False
1   False     True
2   False     True
3    True    False
4    True    False

MultiIndex Series (Decade, Country):
decade   country
Pre-80s  Argentina     0
         Australia     1
         Austria       0
         Bangladesh    0
         Belarus       0
         Belgium       0
         Brazil        0
         Bulgaria      0
         Cambodia      0
         Cameroon      0
dtype: int64

/tmp/ipykernel_8903/3404350162.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  multi_indexed = data.groupby(['decade', 'country']).size().head(10)